knp_snappy:
    pdf:
        enabled:    true
        binary:     "\"C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltopdf.exe\"" #C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf  #'%env(WKHTMLTOPDF_PATH)%'
        options:    []
    image:
        enabled:    true
        binary:     "\"C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltoimage.exe\"" #C:\Program Files\wkhtmltopdf\bin\wkhtmltoimage #'%env(WKHTMLTOIMAGE_PATH)%'
        options:    []
